AWSTemplateFormatVersion: '2010-09-09'
Description: 'Omnichannel Support System - Core Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

Resources:
  # DynamoDB Tables
  TicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'support-tickets-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ticket_id
          AttributeType: S
        - AttributeName: customer_id
          AttributeType: S
        - AttributeName: status_timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: ticket_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CustomerIndex
          KeySchema:
            - AttributeName: customer_id
              KeyType: HASH
            - AttributeName: status_timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: omnichannel-support

  CustomersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'support-customers-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: internal_id
          AttributeType: S
        - AttributeName: channel_identity
          AttributeType: S
      KeySchema:
        - AttributeName: internal_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ChannelIdentityIndex
          KeySchema:
            - AttributeName: channel_identity
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: omnichannel-support

  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'support-agents-${Environment}'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: false
        - Name: name
          Required: true
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub 'support-web-client-${Environment}'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED

  AgentsGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Agents
      Description: Support agents with full access
      UserPoolId: !Ref UserPool

Outputs:
  TicketsTableName:
    Description: DynamoDB Tickets Table Name
    Value: !Ref TicketsTable
    Export:
      Name: !Sub '${AWS::StackName}-TicketsTable'

  CustomersTableName:
    Description: DynamoDB Customers Table Name
    Value: !Ref CustomersTable
    Export:
      Name: !Sub '${AWS::StackName}-CustomersTable'

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'

  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolArn'
