AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Omnichannel Support API

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        DYNAMODB_TICKETS_TABLE: support-tickets-dev
        DYNAMODB_CUSTOMERS_TABLE: support-customers-dev
        COGNITO_USER_POOL_ID: us-east-1_QcMqBPp39
        COGNITO_APP_CLIENT_ID: 3bvao34ggrm8e8sfbjksf0k36t
        COGNITO_REGION: us-east-1
        KAFKA_BOOTSTRAP_SERVERS: localhost:9092

Resources:
  SupportApi:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        ApiProxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: support-tickets-dev
        - DynamoDBCrudPolicy:
            TableName: support-customers-dev
        - Statement:
          - Effect: Allow
            Action:
              - dynamodb:Query
            Resource:
              - arn:aws:dynamodb:us-east-1:*:table/support-tickets-dev/index/*
              - arn:aws:dynamodb:us-east-1:*:table/support-customers-dev/index/*
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.12-v1

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt SupportApi.Arn
